### ISSUE TITLE
Add a cabal file to repo

### ISSUE THREAD

**Issue by ersran9** [google/ghc-source-gen#60]
Right now cabal users cannot use `ghc-source-gen` via a `cabal.project` file as a `source-repository-package` - since it insists on a cabal file. I'd be happy to provide a PR if its okay.

**Comment by judah** [comment]
Thank you for bringing this up.  I would rather not check in the cabal file into this repository since it's generated from the `package.yaml` file.  This issue seems like a limitation of Cabal; in fact I did find an upstream bug to support this kind of setup in `cabal.project` files:
https://github.com/haskell/cabal/issues/5785

If you need to use it from git, I suggest keeping a fork that has the .cabal file.  I'll also attempt to keep the Hackage releases reasonably up-to-date so they can be used directly.

**Comment by ersran9** [comment]
Ah okay. I think we'll keep a fork then as you suggest and close the issue. Thanks for the clarification.
