### ISSUE TITLE
Support list comprehensions

### ISSUE THREAD

**Issue by jinwoo** [google/ghc-source-gen#64]
There doesn't seem to be a way to construct a syntax tree for list comprehensions. Or am I missing something?

**Comment by judah** [comment]
You're right that it's not supported yet. It looks like this would be pretty easy to add though; let me know if you're interested:
http://hackage.haskell.org/package/ghc-8.8.1/docs/HsExpr.html#t:HsExpr

GHC's ADT models list comprehensions with the `HsDo` constructor (the same as for `do` notation). The only difference seems to be that the `HsStmtContext` is `ListComp` instead of `DoExpr`:
https://github.com/google/ghc-source-gen/blob/079fb254dbce6e325c8095e3d604648ab2253429/src/GHC/SourceGen/Expr.hs#L91

I think we could just add a new function `listComp`. It would probably be even simpler than `do'` since it wouldn't have to deal with the let-parenthesization issue (e.g.: `do let ...`).

**Comment by jinwoo** [comment]
Glad to hear from you, Judah!

Yeah, I was thinking of adding this if I was not missing something obvious. I'll write a PR when I can (hopefully soon).
